name: base
channels:
        - conda-forge
        - defaults
dependencies:
        - pandas=0.24.2
        - scikit-learn=0.20.3
        - joblib=0.13.2
        - pip:
                - flask==1.1.1
                - flask_restful
                - flask_cors
                - gunicorn
